# Site
title: krisztiN
url: https://www.kriszt.in

# SEO
logo: /siteicon.png
description: Front-end developer with UX and UI design experience

# Collections
collections:
  case_studies:
    output: true

# Social
github_username: krisztin
linkedin_username: nkriszti
codepen_username: krisztiiin

# Build
permalink: /:category/:title
defaults:
  - scope:
      path: ''
    values:
      layout: 'page'
  - scope:
      path: 'index.html'
    values:
      layout: 'default'

# Plugins
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
