# ----
# Site

title: krisztiN
url: "https://kriszt.in"
? baseurl
? google_analytics_key

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Web dev, UI/UX designer.
author:
  ? Kriszti
  ? me@kriszt.in
social:
  name: krisztiN
  links:
    - https://kriszt.in

# -----
# Build

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
