# Site
title: krisztiN
url: https://kriszt.in

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Front-end developer with UX and UI design experience

# Collections
collections:
  case_studies:
    output: true

# Social
github_username: krisztin
linkedin_username: nkriszti

# Build
permalink: /:category/:title
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
# Plugins
plugins:
  - jekyll-archives
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
